"""Add Lobby Makers support

Revision ID: 12fc01befadd
Revises: f0708fc96070
Create Date: 2025-11-24 20:48:56.222701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12fc01befadd'
down_revision: Union[str, Sequence[str], None] = 'f0708fc96070'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_participants', sa.Column('is_lobby_maker', sa.Boolean(), nullable=True))
    op.add_column('tournament_games', sa.Column('lobby_maker_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tournament_games', 'users', ['lobby_maker_id'], ['id'])
    op.add_column('tournaments', sa.Column('lobby_maker_priority_list', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'lobby_maker_priority_list')
    op.drop_constraint(None, 'tournament_games', type_='foreignkey')
    op.drop_column('tournament_games', 'lobby_maker_id')
    op.drop_column('game_participants', 'is_lobby_maker')
    # ### end Alembic commands ###
