"""add soft delete flag to tournaments

Revision ID: a1b2c3d4e5f6
Revises: 12fc01befadd
Create Date: 2025-11-24 23:02:00.000000
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = '12fc01befadd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # Remove server default after column creation to keep model default behavior
    op.alter_column('tournaments', 'is_deleted', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'is_deleted')
    # ### end Alembic commands ###
