"""add_tournament_settings

Revision ID: ab15cf211903
Revises: 007592814a89
Create Date: 2025-11-25 22:54:45.103133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab15cf211903'
down_revision: Union[str, Sequence[str], None] = '007592814a89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('is_free', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('tournaments', sa.Column('prizes', sa.JSON(), nullable=True))
    op.add_column('tournaments', sa.Column('first_round_strategy', sa.String(), server_default='RANDOM', nullable=True))
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'first_round_strategy')
    op.drop_column('tournaments', 'prizes')
    op.drop_column('tournaments', 'is_free')
    # ### end Alembic commands ###
