"""Initial migration

Revision ID: f0708fc96070
Revises: 
Create Date: 2025-11-24 20:29:31.353293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f0708fc96070'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip dropping tables that don't exist in fresh DB
    # op.drop_table('contact_forms')
    # op.drop_index(op.f('ix_game_sessions_id'), table_name='game_sessions')
    # op.drop_table('game_sessions')
    
    # Skip altering users table if it doesn't exist yet
    # These operations assume the table already exists
    # op.alter_column('users', 'battlenet_id',
    #            existing_type=sa.VARCHAR(length=255),
    #            nullable=False)
    # op.alter_column('users', 'battletag',
    #            existing_type=sa.VARCHAR(length=255),
    #            nullable=False)
    # op.drop_index(op.f('idx_users_battlenet_id'), table_name='users')
    # op.drop_index(op.f('ix_users_email'), table_name='users')
    # op.create_index(op.f('ix_users_battlenet_id'), 'users', ['battlenet_id'], unique=True)
    # op.drop_column('users', 'age')
    
    # For fresh DB, we need to create tables from scratch
    # Import Base and engine to create all tables
    from db import Base, engine
    from models.user import User
    from models.tournament import Tournament
    from models.tournament_participant import TournamentParticipant
    from models.tournament_round import TournamentRound
    from models.tournament_game import TournamentGame
    from models.game_participant import GameParticipant
    
    # Create all tables
    Base.metadata.create_all(bind=engine)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_battlenet_id'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('idx_users_battlenet_id'), 'users', ['battlenet_id'], unique=True)
    op.alter_column('users', 'battletag',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'battlenet_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_table('game_sessions',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('state', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('game_sessions_pkey'))
    )
    op.create_index(op.f('ix_game_sessions_id'), 'game_sessions', ['id'], unique=False)
    op.create_table('contact_forms',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('service', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'new'::text"), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('contact_forms_pkey'))
    )
    # ### end Alembic commands ###
